package com.example.ui

import androidx.compose.runtime.mutableStateOf

object LanguageManager {
    // Shared reactive state for current language (false = English, true = Urdu / Translation)
    val isUrdu = mutableStateOf(false)

    fun toggleLanguage() {
        isUrdu.value = !isUrdu.value
    }

    // Dynamic translation resolver
    fun translate(key: String): String {
        val dict = if (isUrdu.value) urduMap else englishMap
        return dict[key] ?: key
    }

    private val englishMap = mapOf(
        "app_name" to "DinaMarket Pakistan",
        "home_title" to "DinaMarket Pakistan",
        "category_fastfood" to "Fast Food",
        "category_grocery" to "Grocery",
        "category_clothes" to "Clothes",
        "category_cosmetics" to "Cosmetics",
        "category_electronics" to "Electronics",
        "category_rentacar" to "Rent-a-Car",
        "category_all" to "All Categories",
        "search_hint" to "Search products, vendors, locations...",
        "only_left" to "Only %d items left!",
        "in_stock" to "In Stock",
        "out_of_stock" to "Out of Stock",
        "verified_buyer" to "Verified Purchaser",
        "reviews_header" to "Realtime Reviews",
        "add_to_cart" to "Add to Cart",
        "proceed_checkout" to "Proceed to Checkout",
        "switch_seller" to "Switch to Seller Dashboard",
        "switch_buyer" to "Switch to Buyer Mode",
        "cart_heading" to "Your Shopping Cart",
        "cart_empty" to "Your cart is currently empty.",
        "terms_and_policy" to "Legal Policies",
        "terms_legal" to "Terms & Conditions",
        "privacy_legal" to "Privacy Policy",
        "total" to "Total Amount",
        "checkout_heading" to "Secure Localized Checkout",
        "full_name" to "Full Name",
        "phone_number" to "Phone Number (e.g., 03xxxxxxxxx)",
        "exact_location" to "Exact Home Delivery / Self-Pickup Address",
        "wallet_heading" to "Independent Merchant Payment System",
        "wallet_sub" to "Buyers pay independent sellers directly on their regional wallets. Type the 12-digit transaction confirmation ID below.",
        "easypaisa_pay" to "Pay with EasyPaisa",
        "jazzcash_pay" to "Pay with JazzCash",
        "seller_wallet_details" to "Seller Wallet Account",
        "tid_verification" to "12-digit Transaction ID (TID)",
        "submit_order" to "Submit Verified Order",
        "seller_suite_reg" to "Seller Business Suite Setup",
        "business_name" to "Business Name",
        "bio_desc" to "Store Bio & Description",
        "store_logo" to "Store Logo URL",
        "physical_loc" to "Physical Stall / Store Address",
        "contact_email" to "Seller Contact Email",
        "whatsapp_num" to "Official WhatsApp Number (for customer queries)",
        "register_business" to "Launch Storefront Now",
        "inventory_title" to "Merchant Inventory",
        "add_item" to "Add New Product",
        "product_title" to "Product Title",
        "product_desc" to "Full Product Description",
        "base_price" to "Base Price (Rs.)",
        "total_stock" to "Total In-Stock Count",
        "social_link" to "Discord / Web Social Links",
        "add_product_btn" to "Publish Product to Grid",
        "orders_tab_pending" to "Pending verification",
        "orders_tab_confirmed" to "Confirmed & Settled",
        "custom_msg_lbl" to "Notification update for Buyer",
        "verify_confirm_btn" to "Verify and complete order",
        "buyer_notification_inbox" to "System Notification Hub",
        "guest_mode" to "Browsing as Guest",
        "rating_stars" to "Stars",
        "order_counter" to "%d Buyers ordered",
        "legal_notice" to "DinaMarket Pakistan is a decentralized, serverless local marketplace platform built in structural compliance with Pakistan PECA Laws.",
        "success_charge_msg" to "First 5-10 orders are 100% Free as part of basic onboarding. Merchants agree to clear minor commission payments thereafter for continued platform hosting.",
        "self_pickup_delivery" to "All logistics, dispatch, or self-pickup routes are explicitly owned directly by the Merchant / Buyer; DinaMarket maintains no riders.",
        "login_required" to "Firebase Authentication Required",
        "login_email" to "Email Address",
        "login_pwd" to "Secret Password",
        "login_btn" to "Login with Email",
        "signup_btn" to "Register New Credentials",
        "bottom_nav_home" to "Home",
        "bottom_nav_search" to "Search",
        "bottom_nav_cart" to "Cart",
        "bottom_nav_account" to "Account"
    )

    private val urduMap = mapOf(
        "app_name" to "دینا مارکیٹ پاکستان",
        "home_title" to "دینا مارکیٹ پاکستان",
        "category_fastfood" to "فاسٹ فوڈ",
        "category_grocery" to "گروسری",
        "category_clothes" to "کپڑے",
        "category_cosmetics" to "کاسمیٹکس",
        "category_electronics" to "الیکٹرانکس",
        "category_rentacar" to "کرائے کی گاڑی",
        "category_all" to "تمام کیٹیگریز",
        "search_hint" to "پروڈکٹ، دکاندار یا سٹور تلاش کریں...",
        "only_left" to "صرف %d آئٹم باقی ہیں!",
        "in_stock" to "سٹاک موجود ہے",
        "out_of_stock" to "سٹاک ختم ہے",
        "verified_buyer" to "تصدیق شدہ خریدار",
        "reviews_header" to "جائزے اور ریٹنگز",
        "add_to_cart" to "کارٹ میں شامل کریں",
        "proceed_checkout" to "آرڈر کی ادائیگی کریں",
        "switch_seller" to "سیلر ڈیش بورڈ پر جائیں",
        "switch_buyer" to "خریدار موڈ پر واپس جائیں",
        "cart_heading" to "آپ کا شاپنگ کارٹ",
        "cart_empty" to "آپ کا کارٹ بالکل خالی ہے۔",
        "terms_and_policy" to "قانونی پالیسی",
        "terms_legal" to "شرائط و ضوابط",
        "privacy_legal" to "پرائیویسی پالیسی",
        "total" to "کل رقم",
        "checkout_heading" to "مقامی ادائیگی اور آرڈر",
        "full_name" to "پورا نام",
        "phone_number" to "فون نمبر (مثال: 03xxxxxxxxx)",
        "exact_location" to "مکمل ہوم ڈلیوری یا سیلف پک اپ کا پتہ",
        "wallet_heading" to "براہ راست دکاندار کو ادائیگی",
        "wallet_sub" to "خریدار دکاندان کو براہ راست ایزی پیسہ یا جاز کیش کریں اور 12 ہندسوں کا ٹرانزیکشن نمبر نیچے درج کریں۔",
        "easypaisa_pay" to "ایزی پیسہ سے ادائیگی",
        "jazzcash_pay" to "جاز کیش سے ادائیگی",
        "seller_wallet_details" to "سیلر والٹ اکاؤنٹ",
        "tid_verification" to "12 ہندسوں کا ٹرانزیکشن نمبر (TID)",
        "submit_order" to "آرڈر جمع کروائیں",
        "seller_suite_reg" to "سیلر رجسٹریشن",
        "business_name" to "کاروبار کا نام",
        "bio_desc" to "سٹور کی تفصیل",
        "store_logo" to "لوگو کا لنک",
        "physical_loc" to "سٹور کا پتہ",
        "contact_email" to "رابطہ ای میل",
        "whatsapp_num" to "واٹس ایپ نمبر",
        "register_business" to "اپنا سٹور لانچ کریں",
        "inventory_title" to "اپنی اشیاء کا انتظام",
        "add_item" to "نئی پروڈکٹ شامل کریں",
        "product_title" to "پروڈکٹ کا نام",
        "product_desc" to "پروڈکٹ کی تفصیل",
        "base_price" to "قیمت (روپے)",
        "total_stock" to "کل سٹاک کی تعداد",
        "social_link" to "ڈسکارڈ یا ویب لنک",
        "add_product_btn" to "پروڈکٹ گرڈ پر شائع کریں",
        "orders_tab_pending" to "تصدیق کی ضرورت ہے",
        "orders_tab_confirmed" to "تصدیق شدہ آرڈرز",
        "custom_msg_lbl" to "خریدار کے لیے پیغام",
        "verify_confirm_btn" to "آرڈر کی تصدیق مکمل کریں",
        "buyer_notification_inbox" to "نوٹیفکیشن سینٹر",
        "guest_mode" to "غیر رجسٹرڈ خریدار",
        "rating_stars" to "ستارے",
        "order_counter" to "%d خریداروں نے آرڈر کیا",
        "legal_notice" to "دینا مارکیٹ پاکستان ایک غیر مرکزی مقامی ڈیش بورڈ ہے جو پاکستان پیکا قوانین کے مطابق ڈیزائن کیا گیا ہے۔",
        "success_charge_msg" to "پہلے 5-10 آرڈرز بالکل مفت ہیں۔ بعد میں دکاندار تھوڑا سا سروس چارج ادا کرنے پر راضی ہیں۔",
        "self_pickup_delivery" to "ڈلیوری کا انتظام مکمل طور پر دکاندار اور خریدار کی ذمہ داری ہے؛ دینا مارکیٹ کے پاس رائیڈرز نہیں ہیں۔",
        "login_required" to "لاگ ان ہونا لازمی ہے",
        "login_email" to "ای میل پتہ",
        "login_pwd" to "پاس ورڈ",
        "login_btn" to "لاگ ان کریں",
        "signup_btn" to "نیا اکاؤنٹ بنائیں",
        "bottom_nav_home" to "گھر",
        "bottom_nav_search" to "تلاش",
        "bottom_nav_cart" to "کارٹ",
        "bottom_nav_account" to "اکاؤنٹ"
    )
}
